name: Hourly AccuWeather Automation

# This triggers the test to run automatically
on:
  schedule:
    - cron: '30  * * * *'

  # Allows you to click a button in GitHub to run it manually at any time
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv (package manager)
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          uv run playwright install chromium --with-deps

      - name: Run AccuWeather Tests (Virtual Headed Mode)
        run: |
          source .venv/bin/activate
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" \
            uv run pytest tests/test_accuweather.py -n 3 --reruns 1 --reruns-delay 3 -p no:cacheprovider -v -rap --tb=short --durations=0 --color=yes -s

      - name: Upload Test Output & CSVs
        if: always() # Uploads the CSVs and Logs even if the test fails
        uses: actions/upload-artifact@v4
        with:
          name: accuweather-test-results
          path: output/
          retention-days: 7
